apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-pvc
  namespace: ml-project
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: ml-training-job
  namespace: ml-project
spec:
  template:
    spec:
      containers:
      - name: trainer
        image: ml-trainer:v1
        imagePullPolicy: Never  # Importante: Usa la imagen local
        volumeMounts:
        - name: storage
          mountPath: /mnt/model
      restartPolicy: Never
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: model-pvc
  backoffLimit: 4
